### ISSUE TITLE
Explain pros/cons of no header keys?

### ISSUE THREAD

**Issue by taoeffect** [wireapp/proteus#4]
Very cool project! Congratulations on making what (I think) is the first Rust axolotl implementation! I see that it's slightly different, and was wondering if the README could elaborate on what exactly that difference implies?

**Comment by romanb** [comment]
The "no header keys" variant is mentioned in the [Axolotl specification](https://github.com/trevp/axolotl/wiki#variations). Header keys seem to be used to hide protocol metadata (e.g. N / PN counters) which,  in the context of Wire, does not provide any benefit because it has already more metadata than that anyway (e.g. who sends messages to whom).

**Comment by taoeffect** [comment]
OK thanks much!
